name: CritiPixel CI

on:
  push:
    branches:
      - main
      - p14-exercice-2

  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Admin123
          POSTGRES_DB: criti_pixel
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      APP_ENV: test
      DATABASE_URL: "postgresql://postgres:Admin123@127.0.0.1:5432/criti_pixel?serverVersion=17.0&charset=utf8"
      SYMFONY_PHPUNIT_LOCALE: fr_FR
      LANG: fr_FR.UTF-8
      LC_ALL: fr_FR.UTF-8

    steps:
      - name: Checkout du projet
        uses: actions/checkout@v4

      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pgsql, pdo_pgsql
          coverage: none

      - name: Installation des dépendances
        run: composer install --no-interaction --prefer-dist

      - name: Préparation de la base de test
        run: |
          php bin/console doctrine:database:drop -f --if-exists --env=test
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate -n --env=test
          php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test

      - name: Analyse statique avec PHPStan
        run: php -d memory_limit=1G vendor/bin/phpstan analyse

      - name: Exécution des tests PHPUnit
        run: vendor/bin/phpunit